### ISSUE TITLE
Example code doesn't work

### ISSUE THREAD

**Issue by jojoyuji** [marmelab/FakeRest#21]
```
<script src="/path/to/FakeRest.min.js"></script>
<script src="/path/to/sinon.js"></script>
<script type="text/javascript">
var data = {
    'authors': [
        { id: 0, first_name: 'Leo', last_name: 'Tolstoi' },
        { id: 1, first_name: 'Jane', last_name: 'Austen' }
    ],
    'books': [
        { id: 0, author_id: 0, title: 'Anna Karenina' },
        { id: 1, author_id: 0, title: 'War and Peace' },
        { id: 2, author_id: 1, title: 'Pride and Prejudice' },
        { id: 3, author_id: 1, title: 'Sense and Sensibility' }
    ],
    'settings': {
        language: 'english',
        preferred_format: 'hardback',
    }
};
// initialize fake REST server
var restServer = new FakeRest.Server();
restServer.init(data);
// use sinon.js to monkey-patch XmlHttpRequest
var server = sinon.fakeServer.create();
server.respondWith(restServer.getHandler());
</script>
```

throws "FakeRest.min.js:1 Uncaught Error: Can't initialize a Collection with anything else than an array of items"

using via bower and sinon installed via: 
`devDependencies: {
  "sinon-server": "http://sinonjs.org/releases/sinon-server-1.14.1.js"
}`

**Comment by blocknotes** [comment]
I got similar problems, try directly with "http://sinonjs.org/releases/sinon-1.17.3.js"

**Comment by jojoyuji** [comment]
Tried using directly as @blocknotes suggested, still the same error :(

**Comment by bgloff** [comment]
@jojoyuji It's complaining because 'settings' is not an array so if you just delete that part (or turn it into a proper array of objects), it'll start working.  You probably got past this already but maybe it will help someone else looking at this for the first time.

**Comment by billgloff** [comment]
@jojoyuji It's complaining because 'settings' is not an array so if you just delete that part (or turn it into a proper array of objects), it'll start working. You probably got past this already but maybe it will help someone else looking at this for the first time.

**Comment by jbaranski** [comment]
I was going to fix this but it doesn't appear to be an issue anymore. Using a plain settings object no error is thrown.

**Comment by jojoyuji** [comment]
haha, I endup using dyson.js, well thx anyway
