### ISSUE TITLE
ng-admin example

### ISSUE THREAD

**Issue by RaniaSalah** [marmelab/FakeRest#24]
<script src="bower_components/sinon-server/index.js" type="text/javascript"></script>

Please I want to know what is index.js file ??
and when I add this <script> tag it's now working
so where is the problem ,please?

**Comment by fzaninotto** [comment]
did you run `bower install`, as explained in the readme?

**Comment by RaniaSalah** [comment]
@fzaninotto  Yes, I did so I don't know where the problem

**Comment by fzaninotto** [comment]
It's probably because ng-admin is no longer published on bower... So this example needs fixing.
