### ISSUE TITLE
FakeRest throws Array.findIndex() error while using it on IE and Edge 

### ISSUE THREAD

**Issue by ashwanikumar415** [marmelab/FakeRest#25]
Included fakeRest via npm in project . But now when the same app runs on IE or Edge throws the below error:
`Object doesn't support property or method 'findIndex' 
File: FakeRest.min.js, Line: 1, Column: 14642
`
Was this intentional not to support IE ?

**Comment by fzaninotto** [comment]
No, it's IE's lack of support for modern JS that is intentional ;)

**Comment by ashwanikumar415** [comment]
Well in that case , only workaround left is to use below polyfill and load it before fakeRest in html 

` if (!Array.prototype.findIndex) {
  Object.defineProperty(Array.prototype, 'findIndex', {

    value: function(predicate) {
      if (this == null) {
        throw new TypeError('"this" is null or not defined');
      }
      var o = Object(this);
      var len = o.length >>> 0;
      if (typeof predicate !== 'function') {
        throw new TypeError('predicate must be a function');
      }
      var thisArg = arguments[1];
      var k = 0;
      while (k < len) {
        var kValue = o[k];
        if (predicate.call(thisArg, kValue, k, o)) {
          return k;
        }
        k++;
      }
      return -1;
    }
  });
} `

**Comment by ashwanikumar415** [comment]
@fzaninotto 
Is it feasible to add the above-mentioned piece of polyfill in your code? So that fake rest runs everywhere flawlessly? And consumers of fakeRest don't have to bother to add polyfill just to make it work?

**Comment by fzaninotto** [comment]
Of course! Would you like to make a Pull Request?

**Comment by ashwanikumar415** [comment]
@fzaninotto 
sure !!! that'll be great . We install fakeRest via npm in our project

**Comment by fzaninotto** [comment]
No news for some time, closing.
